language: node_js
node_js:
  - "8"
branches:
  only:
    - master
services:
  - docker
install:
  - npm install
script:
  - npm run build
cache:
  directories:
    - node_modules
addons:
  ssh_known_hosts: 39.99.130.5
after_success:
  - docker build -t chenxiaoyue/chester-web-plc-manager:laster .
  - docker login -u $docker_name -p $docker_pwd
  - docker push chenxiaoyue/chester-web-plc-manager:laster
  - ssh $machine_name@$machine_ip
  - cd /root
  - docker-compose pull web-plc-manager
  - docker-compose up -d
before_install:
  - openssl aes-256-cbc -K $encrypted_9b2d7e19d83c_key -iv $encrypted_9b2d7e19d83c_iv
    -in id_rsa.enc -out ~\/.ssh/id_rsa -d