language: node_js
node_js:
  - "8"
services:
  - docker
install:
  - npm install
script:
  - npm run build
cache:
  directories:
    - node_modules
after_success:
  - docker build -t chenxiaoyue/chester-web-plc-manager:laster .
  - docker login -u chenxiaoyue -p tom36634938@qq
  - docker push chenxiaoyue/chester-web-plc-manager:laster